-- AlterEnum
ALTER TYPE "OrderStatus" ADD VALUE 'PARTIALLY_ACCEPTED';
ALTER TYPE "OrderStatus" ADD VALUE 'FULFILLING';

-- AlterTable
ALTER TABLE "Order" ADD COLUMN "productId" TEXT;
ALTER TABLE "Order" ADD COLUMN "requestedQty" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Order" ADD COLUMN "acceptedQty" INTEGER;
ALTER TABLE "Order" ADD COLUMN "unitPrice" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN "requiredBy" TIMESTAMP(3);

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;
