spring.application.name=core-api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

internal.api-key=${INTERNAL_API_KEY}
ml-service.base-url=${ML_SERVICE_BASE_URL}
realtime-service.base-url=${REALTIME_SERVICE_BASE_URL}
